# -- Main Menu --

[[main]]
    name = "About"
    pageRef = "about"
    weight = 2

[[main]]
    name = "Projects"
    pageRef = "projects"
    weight = 3

[[main]]
    name = "MIRAI"
    pageRef = "mirai"
    weight = 4

# -- Footer Menu --

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
